### PR TITLE
Add tests about number of clusters inconsistency

### PR DESCRIPTION
**Pull request by Croshiw**

### CODE REVIEW

**Comment by Croshiw** [comment]
One of the tests if skipped as #10 is not yet implemented

**Comment by jordanmontt** [comment]
Can you please tell me which tests did you added/modified? Because I cannnot see the changes here in the PR. It shows that everything was added.

**Comment by Croshiw** [comment]
@jordanmontt
added : testNumberOfClustersCentersMatchExpectation, testInconsistentNumberOfClusters, testNumberOfClustersCantBeNegative, testNumberOfClustersCantBeSuperiorToNbData, testNumberOfClustersCantBeZero
changed: just the formatting of old tests not the content

**Comment by jordanmontt** [comment]
I just talked with Oleks and we agreed that is not necessary to check, for example, if the number of cluster is not negative, is not zero, etc... Also in Pharo is considered a bad practice to type check.

So, can you please delete the tests please:

- testInconsistentNumberOfClusters
- testNumberOfClustersCantBeNegative
- testNumberOfClustersCantBeSuperiorToNbData

**Comment by jordanmontt** [comment]
and also can you rename the variable `nbClusters`to only `clusters` in the test: `testNumberOfClustersCentersMatchExpectation` ?

**Comment by jordanmontt** [comment]
And finally rename the test `testNumberOfClustersCentersMatchExpectation` to `testNumberOfCentroidsMatchExpectation`

Thanks !

**Comment by jordanmontt** [comment]
Thank you @Croshiw :)

**Pull request merged**
